server:
  port: 11002
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xiaomo?characterEncoding=utf8&useSSL=false
    password: root
    username: root
